image: openjdk:11-jdk-slim

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - app/build/libs/*.jar

test-job:
  stage: test
  script:
    - gradlew test
  artifacts:
    when: always
    reports:
      junit: app/build/test-results/test/**/TEST-*.xml
